# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8e852a2c8cbf8b1dc7c9688204ca33cc02a1d00761127983f4cc7c00cd59c96b683955e50694045137bf937519e6ab20819665ab6e6f11357275cc9cf79ad4a

test:
  secret_key_base: df123af579aa7d3a05974de227b6a5e4f178786c5122d167c2f14387ea7576c39924d84e19327969dceac9b6aee28b2f5b8aba1ef51f4eb6eb902cb376deda66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
